### PR TITLE
Updates dependencies to latest minor release

### PR DESCRIPTION
**Pull request by manuelroth**
Hi @susielu,
This PR updates all the dependencies to the latest minor release and adds the `^` to specify that[ minor release updates should be accepted](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept).
I did run the tests locally and they were all green. Please let me know if other files need to be added for this change.

Kind regards,
Manuel

### CODE REVIEW

**Comment by susielu** [comment]
Hi Manuel, is there a specific feature in the latest versions that you're interested in using with d3-annotation?

**Comment by manuelroth** [comment]
There is a problem in d3-drag (before v1.2.0) with passive event listeners in Chrome mobile test mode. [See this issue](https://github.com/d3/d3-drag/issues/41) for more context. This issue makes dragging the annotations around very sluggish. Upgrading to v1.2.3 would fix that

Bildschirmfoto 2019-03-24 um 16 59 23

**Comment by susielu** [comment]
@manuelroth thanks for explaining your use case some more. I upgraded the d3-drag library to a version to `1.2.3` but kept the versions specific and downgraded some of the other versions you changed. This is now published with the upgrade as `v2.4.0`.

I like to keep the dependencies as stable as possible to reduce the possibility of unwanted mistakes or issues arising simply due to version bumps that I am unaware of so I tend to steer clear of the `^` when possible.

**Comment by manuelroth** [comment]
I understand. Thank you very much for creating a release

**Comment by manuelroth** [comment]
@susielu after the release of `v2.4.0` I am getting [this error](https://github.com/susielu/d3-annotation/issues/24). As I understand it, it has to do with declaring multiple versions of d3-selection (v1.0.6 and v1.4.0) in [yarn.lock](https://github.com/susielu/d3-annotation/blob/master/yarn.lock#L1580). Could it be that you have to run `yarn install` and update the bundle again?

**Comment by susielu** [comment]
Thanks for digging into this, taking a look now.

**Comment by susielu** [comment]
I published a version `v2.5.0` that upgrades to `d3-selection@1.4.0` so there are no duplicate versions anymore. Let me know if you still see this issue.

**Comment by manuelroth** [comment]
Thank you very much. The issues is resolved 🎉

**Pull request merged**
